language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "c-ar-d-server-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  # - npm run build-client # make the bundle  # repo only serves as a server, webpack not needed
# before_deploy:
#   - rm -rf node_modules # omit from the tarball, since we skip cleanup
# deploy:
#   skip_cleanup: true # prevents travis from deleting the build
#   provider: heroku
#   app: YOUR-HEROKU-APP-NAME-HERE # see README
  api_key:
    secure: NVgykIwLfq8mP2ebYoFigRbi6brC3eh1+VU3thr2wkbNubaaC4OCxZ0G49m03UrNXSb2hL3+hu0BarveocUJtraX8ho/jwFwwc90XpxzzaR0i3clzYkZIEhC/Nm77aXXhkstzkoooz3dT2umNr+/hq++aZxl/tm6wMeegcFTkw76+xtqoXPhkbf5vDqmRhvTUEROSvv955ITZgeJwv6IchfLPvlbhUmCM4I0UKSugGuG6CjEvrxEbzHvAoUTwqAkzkg/hGC1P7NntC4nrtDQG13EYKxz8yNGjOd8++iIeSQUIikTbCLAyQZGmzhAo6rW+p388APDDKrhHe1GaFaMNS0u/uMfCKmWSTK7SYpGfaKJoUqJKTAEAG4jnVnqZRYN3BiJnOk6zQXtAKwD+ZPFT2h71Y2sNYMwMm7MwzEjEpjcN5tAZALw5FntBj+iV4henW41JvykEm2iV307hImjKja9vf4KTbOylsNA4GOrPh0+XrjbfTbUfHZtXwcZXgPg+xGXt8xolR14/Nrizkawlb79O0w92hxuiMDuALluwnUPC88/HA8p0nam8PFlB38u0ArU/mGThmr4UCmtdug44S3bgZm+ZmULC1Xl9hjZZaSXIeuzz9K7dLhy5IB5NMonNAT6cggrM5bclbgTtQkRDPxz8iSYB147rYNUlZ7ajbA=
